.PHONY: build
build:
	docker build \
		--platform linux/amd64 \
		--tag 936543636223.dkr.ecr.us-east-1.amazonaws.com/eks-playground:latest \
		.

.PHONY: push
push:
	docker push 936543636223.dkr.ecr.us-east-1.amazonaws.com/eks-playground:latest
